// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNnxfurnRiInea5j9R1Nxsl6MnZZkSbXY',
    appId: '1:320595986184:web:db26640f6ea9b1a4ddcebd',
    messagingSenderId: '320595986184',
    projectId: 'we-chat-bff75',
    authDomain: 'we-chat-bff75.firebaseapp.com',
    storageBucket: 'we-chat-bff75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-IOQbbLPnfeaB0APl0RCsllAIZGkw8tk',
    appId: '1:320595986184:android:c34a15e82d2eef15ddcebd',
    messagingSenderId: '320595986184',
    projectId: 'we-chat-bff75',
    storageBucket: 'we-chat-bff75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP3k0aX6QUVkCTsCP-AOtG66uS1gE5dgM',
    appId: '1:320595986184:ios:2f8553016cd1cd47ddcebd',
    messagingSenderId: '320595986184',
    projectId: 'we-chat-bff75',
    storageBucket: 'we-chat-bff75.appspot.com',
    androidClientId: '320595986184-2lhtnpasc84okh715lspmslaq9s1vqar.apps.googleusercontent.com',
    iosClientId: '320595986184-nbfjhmo47o1kj1s2n5th4cm8g0sqof8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP3k0aX6QUVkCTsCP-AOtG66uS1gE5dgM',
    appId: '1:320595986184:ios:451bab3abc243622ddcebd',
    messagingSenderId: '320595986184',
    projectId: 'we-chat-bff75',
    storageBucket: 'we-chat-bff75.appspot.com',
    androidClientId: '320595986184-2lhtnpasc84okh715lspmslaq9s1vqar.apps.googleusercontent.com',
    iosClientId: '320595986184-oqimpdfa6mj8v1jiv2oo5m9lnia50fcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat.RunnerTests',
  );
}
